### ISSUE TITLE
必要な機材の検討

### ISSUE THREAD

**Issue by radiocat** [kaigi-no-owari/room#1]
会議の終わりに会議室で通知するためのデバイス

必要な機能
- wifiやBluetoothなどの通信機能
- 音や光などの通知機能

**Comment by radiocat** [comment]
このへんがあればだいたいのことはできそう
http://www.microfan.jp/esp8266/esp8266-blade
http://store.shopping.yahoo.co.jp/microfan/trial-esp8266-blade-esp-kit.html

**Comment by radiocat** [comment]
鳥の鳴き声のモジュール
http://www.mycomkits.com/SHOP/MK-151.html

**Comment by radiocat** [comment]
ESP-WROOM-02を使って何かを制御する感じ

ESPr Developer ( ESP-WROOM-02 開発ボード )の使い方をザッと紹介
https://www.mgo-tec.com/blog-entry-ss-wroom-howto01.html
⇒スマホのブラウザでリクエストを投げてLチカする方法が紹介されている

ESP-WROOM-02にカメラモジュールを繋いでネットワークカメラを作る
http://qiita.com/binzume/items/e301c12b7ec1486d7c42
⇒カメラの制御

**Comment by radiocat** [comment]
http://deviceplus.jp/hobby/entry0032/

最低限必要そうなもの
- ESP-WROOM-02本体 http://www.microtechnica-shop.jp/shopdetail/000000000039/ct9/page1/order/
- ブレッドボード http://www.sengoku.co.jp/mod/sgk_cart/detail.php?code=3DBC-TCK4
- ジャンパピン(2mmピッチ) http://akizukidenshi.com/catalog/g/gP-03902/
- ピンヘッダ(2.54mmピッチ、2mmピッチ) http://akizukidenshi.com/catalog/g/gC-00167/
- 低電圧レギュレーターLDO 3.3v http://akizukidenshi.com/catalog/g/gI-09119/

**Comment by radiocat** [comment]
## ESP-WROOM-02

はんだ付け不要！すぐに使えるWiFiモジュールスターターボード
https://fabcross.jp/news/2016/03/20160315_megatech_espwroom02.html

ハンダ付け不要！初心者でもできる、30分おきにセンサーの値をWeb上に保存する仕組みを安定して動かす（回路編）
http://blog.mlkcca.com/iot/save-sensor-values-by-half-hour/

① http://www.amazon.co.jp/dp/B01COLZT76

---

ブレッドボードにつける場合はハンダ付け必要、直挿しなら不要

②　ESPr Developer（ESP-WROOM-02開発ボード）
http://www.amazon.co.jp/dp/B017U73IFE

③　ESPr One（Arduino Uno同一形状 ESP-WROOM-02開発ボード）
http://www.amazon.co.jp/dp/B01C8A3X3U

④　ESPr Developer（ピンソケット実装済）
http://www.amazon.co.jp/dp/B01ESFQFI8

---
- USBから電源供給（wifiモジュールとしては電源類のパーツは不要）
- 最悪ブレッドボード不要

---

ブレッドボードに挿すなら①
Arduinoと同じ形状のほうが扱いやすいなら③
ソケット挿しで使うなら③④

③が色んなケースに対応しやすいかも

**Comment by radiocat** [comment]
周辺パーツ

ラズパイ向けだけどいけるはず

① ハック ラズベリーパイ Raspberry Pi 電子工作入門キット。
http://www.amazon.co.jp/dp/B00G86DOP8
圧電スピーカーでなにがしかの音が鳴らせるかも。電池ボックス有り。
部品が入ってなかったというコメント有り。

② Raspberry Piで学ぶ電子工作 専用 実験キット スターターパック 
http://www.amazon.co.jp/dp/B01AUN1JYW
電池ボックス有り。LCD有り。種類がたくさん。何かはできそう。
部品が全部入ってないというコメントがある。

③ Raspberry Pi電子工作エントリーキット -Physical Computing Lab 
http://www.amazon.co.jp/dp/B00MRQ5U1Y
圧電スピーカー有り、種類豊富。

---

Arduino向け

④ Arduino拡張キット- Physical Computing Lab
http://www.amazon.co.jp/dp/B008QUJALG
LCD有り。

⑤ SunFounder(サンファウンダー) 助手基礎のスターターキット Arduino UNO R3 Mega2560 Mega328 Nanoのために [並行輸入品] 
http://www.amazon.co.jp/dp/B00DGNZ9G8
種類豊富、ブザー有り

---

ラズパイ版なら③が無難かも。②の豊富さは惹かれるけど評価が悪いので微妙。
Addition版なら⑤のほうが種類が多くてケース入りなので後々備品として使うのにも便利かも。

**Comment by oohira** [comment]
- 大前提として、Raspberry Pi なら音もネットもモーターも困らないだろうが面白くないので、使わない
- 将来的に会議室毎の量産を考えると ESP-WROOM-02 で実現できるならコストを抑えられる
  - が、そのまま回路組めるほどモヒカンではないので、いったん開発ボードで試作する
  - 音を鳴らせない問題があるので、そのへんやりだすと結局 Raspberry Pi では？という話になりそうだが、1つ目の理由により却下
- サーボモーター SG90 は動作電圧 4.8〜5.0V
  - http://akizukidenshi.com/catalog/g/gM-08761/
  - ESPr One の動作電圧が 3.3V なので SG90 の制御用信号に使えるか微妙。ネット上では、3.3V くらいでも大丈夫という記事がなくはない
    - http://qiita.com/yoneken/items/8667be9d40d29a295085
    - https://www.youtube.com/watch?v=fU_5Zx-L-g8
  - ESPr One の 5.0V 出力を使えば、SG90 の電源の方は確保できると思う。が、ぎりぎりなので本体の動作が不安定になるかもしれない。周辺パーツは、予備電源用の電池BOX付きのセットの方が無難かも

このへんの知識がなさ過ぎてつらい。やってみるしか

**Comment by oohira** [comment]
次の2つを手配済み

> ③　ESPr One（Arduino Uno同一形状 ESP-WROOM-02開発ボード）
> http://www.amazon.co.jp/dp/B01C8A3X3U
> 
> ③ Raspberry Pi電子工作エントリーキット -Physical Computing Lab 
> http://www.amazon.co.jp/dp/B00MRQ5U1Y
