### ISSUE TITLE
スケジュール情報を取得する方法の調査

### ISSUE THREAD

**Issue by oohira** [kaigi-no-owari/room#2]
会議の予定を取得できるか調査する。
- 「開始日時」「終了日時」「会議室名」の3つが最低限
- 個人のアカウントで認証して取得？
- 個人のスケジュールなら iCal で取れそうだけど、会議室は無理か
  - https://www.desknets.com/neo/download/doc/ical/start.html

**Comment by oohira** [comment]
> 個人のスケジュールなら iCal で取れそうだけど、会議室は無理か

APIの口は開放されているが、自分のスケジュールしか返ってこなかったので、やはり使えなさそう。

**Comment by radiocat** [comment]
PhantomJS でログインが必要なページでも自由自在にスクレイピング
http://tips.hecomi.com/entry/20121229/1356785834

**Comment by oohira** [comment]
PhantomJS 直接でいくよりは、CasperJS をかぶせた方が楽だと思われ。
- http://casperjs.org/

**Comment by radiocat** [comment]
どっちも使ったことなくて、キャプチャを撮るならみたいな情報が多いけどCasperJSのほうが便利なんですかね。アイコンはなんかちょっとイラッと来るね。

**Comment by oohira** [comment]
CasperJSをローカルPCで定期実行する方針に決定
- https://github.com/kaigi-no-owari/nakajin
