### ISSUE TITLE
鳩時計購入検討

### ISSUE THREAD

**Issue by radiocat** [kaigi-no-owari/room#3]

**Comment by oohira** [comment]
IoT対応の鳩時計はありそうでない。プロトはあるけど入手できなさそう。
- スマート鳩時計
  - https://www.amidus.jp/product/smart-hatodokei/

自作したという話は↓がほぼイメージ通り。
- スマート鳩時計の作り方(スマート鳩時計の紹介＆サーボモータ制御編)
  - http://blog.mylab.jp/20151207.html

無印の鳩時計（音がすごくよい）を鳴らすんではなくて黙らせる、という話はある。
- 無印良品の鳩時計を黙らせる電子工作
  - http://qiita.com/pm11op/items/99dbff6c497eb197b1c3

**Comment by oohira** [comment]
- 案1. API付きの鳩時計を調達する
  - 製品レベルのものはないので困難
- 案2. 普通の鳩時計＋スイッチを物理的に押す装置
  - 鳩時計自体が高く、予算オーバー
  - 逆に鳴らさないようにする仕組みも考えなければならない
- 案3. 鳩時計っぽいものを自作する
  - 鳩が動く部分が本質なので、その装置を自作する
  - サーボモーターか普通のモーターで何かしら動く仕組みは作れるはず

案3.で進める。モーターは #1 で調達する。
