### ISSUE TITLE
Lチカまで

### ISSUE THREAD

**Issue by oohira** [kaigi-no-owari/room#5]
1. Arduino IDE のインストール
   - https://www.arduino.cc/en/Main/Software
   - Mac OS X 用 v1.6.9
2. ESP-WROOM-02 用の Arduino IDE 設定
   - http://trac.switch-science.com/wiki/esp_dev_arduino_ide
   - https://www.mgo-tec.com/blog-entry-ss-wroom-howto01.html
3. PC と ESP-WROOM-02 の接続
4. AT コマンドで接続確認
   
   ```
   rl��r��#�n ...（略）
   ready
   AT
   
   
   OK
   AT+GMR
   
   AT version:0.40.0.0(Aug  8 2015 14:45:58)
   SDK version:1.3.0
   compile time:Aug 11 2015 17:02:18
   OK
   ```
5. Lチカ用の配線
   - http://qiita.com/dz_/items/27c2e19981e0bcddcf66
6. 「Blink」サンプルプログラムの書き込み
   - サンプルプログラムを書き込んだので、おそらくもうATコマンドは使えない

**Comment by oohira** [comment]
13番ピン → 抵抗 (10kΩ) → LED → GND

![image](https://cloud.githubusercontent.com/assets/4208984/16495287/bbfef182-3f27-11e6-8bba-43f646ed20b0.png)

**Comment by radiocat** [comment]
いけるやん！
